### ISSUE TITLE
[BUG] cudf.Series.duplicated returns error 'Series' object has no attribute 'duplicated'

### ISSUE THREAD

**Issue by tiraldj** [rapidsai/cudf#15777]
**Describe the bug**
I am trying to see if there are duplicate values in a feature within a dataframe using [duplicated()](https://docs.rapids.ai/api/cudf/nightly/user_guide/api_docs/api/cudf.series.duplicated/)

**Steps/Code to reproduce bug**

first i tried using the duplicated() on the column itself

`df['job_title'].duplicated()
`
then explicitly made it a series of string values then ran duplicated().
`dups = cudf.Series(df['job_title']).astype('string')

dups = dups.duplicated()
`
in these cases i get the error: 'Series' object has no attribute 'duplicated'

**Expected behavior**
Something like this, where 'True' means duplicate of something that came before:

0    False
1    False
2     True
3    False
4     True
dtype: bool

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)] Cloud (Paperspace, RAPIDS image)
 - Method of cuDF install: [conda, Docker, or from source] image came with cudf preinstalled

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details
I couldn't run the print_env.sh, wasn't found in the directory

nvidia-smi says: NVIDIA-SMI 525.116.04   Driver Version: 525.116.04   CUDA Version: 12.0  
I was using a P5000 on paperspace

**Additional context**

**Comment by mroeschke** [comment]
Thanks for the report. Could you share what version of cudf you are running as well as a reproducible example? For example, this works on cudf 24.04

```python
>>> import cudf
>>> cudf.Series(list("121")).duplicated()
0    False
1    False
2     True
dtype: bool
>>> cudf.__version__
'24.04.00'
```

**Comment by tiraldj** [comment]
thank you for the reply

cudf.__version__  says '22.10.01+2.gca9a422da9'

again this is the Paperspace cloud service's RAPIDS image

**Comment by mroeschke** [comment]
I do not see `duplicated` implemented for `22.10.01` so that's the reason for the failure.

It appears `23.02` is the first release where `duplicated` is implemented.

**Comment by tiraldj** [comment]
thank you for the clarification

**Comment by mroeschke** [comment]
Closing as the OP was the expected behavior given the cudf version
