### ISSUE TITLE
[BUG] Series.values_host removal breaks `holoviews`

### ISSUE THREAD

**Issue by jameslamb** [rapidsai/cudf#22859]
**Describe the bug**

https://github.com/rapidsai/cudf/pull/22649 removed `Series.values_host`.

The latest released version of `holoviews` appears to rely on that. That project has a fix merged (https://github.com/holoviz/holoviews/pull/6852) but it hasn't yet made it into a release.

Just opening this to inform you of that breakage.

**Steps/Code to reproduce bug**

Don't have a clean reproducible example, but see https://github.com/rapidsai/cuxfilter/pull/793#issuecomment-4684889837

```text
File /opt/conda/envs/docs/lib/python3.14/site-packages/holoviews/core/data/cudf.py:141, in cuDFInterface.values(cls, dataset, dim, expanded, flat, compute, keep_index)
    139     return data
    140 elif compute:
--> 141     return data.values_host
    142 try:
    143     return data.values

AttributeError: 'Series' object has no attribute 'values_host'
```

**Expected behavior**

I'm not sure if this is known.

There are `holoviews` integration tests and they appear to have been passing ([example](https://github.com/rapidsai/cudf/actions/runs/27369097335/job/80881422617#step:13:9312)), so maybe this an indication that they should be expanded?

Or maybe this is a known thing and breaking that API is a calculated risk... I don't know, just opening to inform you all.

cc @mroeschke 

**Environment overview (please complete the following information)**

N/A

**Environment details**

N/A

**Additional context**

Noticed in `cuxfilter` CI (https://github.com/rapidsai/cuxfilter/pull/793#issuecomment-4684889837), but don't make any decisions here for the benefit of that project... its 26.06 release works well with cuDF 26.06 and the latest `holoviews`, and no future releases are planned: 

* https://docs.rapids.ai/notices/rsn0060/
* https://github.com/rapidsai/build-planning/issues/291

**Comment by mroeschke** [comment]
Thanks for the report. Yeah this was deprecated in 26.04, https://github.com/rapidsai/cudf/pull/21346, and is intended to be removed in the next release

We do run our third party holoview tests with [`-W error`](https://github.com/rapidsai/cudf/blob/a643d62fc5c356e7fd4549cd308f3e0385921be4/ci/cudf_pandas_scripts/third-party-integration/run-library-tests.sh#L24) so we should have seen break our tests if we had coverage but I suppose we didn't :/
