### ISSUE TITLE
[BUG] groupby apply on a functools.partial func fails

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#13426]
**Describe the bug**
When using groupby apply on a function wrapped via functools partial I run into `AttributeError: 'functools.partial' object has no attribute '__code__'`

**Steps/Code to reproduce bug**
```python
import cudf
from functools import partial

df = cudf.DataFrame({"a":[1,2,3]})

def func(df):
    return df.sum()

df.groupby("a").apply(func) # works

func2 = partial(func)
df.groupby("a").apply(func2) # fails
```

**Expected behavior**
No failures as this use to work in previous nightlies/23.04

**Environment overview (please complete the following information)**
 - 23.06 nightlies
 - conda installed
 
**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**
It's most likely related to the latest numba 0.57 update since it started happening very recently seen in dask-sql [tests](https://gpuci.gpuopenanalytics.com/job/dask/job/dask-sql/job/prb/job/dask-sql-prb/2794/CUDA_VER=11.5,LINUX_VER=ubuntu18.04,PYTHON_VER=3.9,RAPIDS_VER=23.06/testReport/junit/tests.unit/test_queries/test_gpu_query_q53_sql_/).

**Comment by bdice** [comment]
Here's the traceback.

```
Traceback (most recent call last):
  File "/raid/bdice/compose-environments/rapids1/t.py", line 12, in <module>
    df.groupby("a").apply(func2) # fails
  File "/raid/bdice/compose-environments/rapids1/compose/etc/conda/cuda_11.8/envs/rapids/lib/python3.10/site-packages/nvtx/nvtx.py", line 101, in inner
    result = func(*args, **kwargs)
  File "/raid/bdice/compose-environments/rapids1/cudf/python/cudf/cudf/core/groupby/groupby.py", line 1354, in apply
    if (not grouped_values._has_nulls) and _can_be_jitted(
  File "/raid/bdice/compose-environments/rapids1/cudf/python/cudf/cudf/core/udf/groupby_utils.py", line 221, in _can_be_jitted
    _get_udf_return_type(dataframe_group_type, func, args)
  File "/raid/bdice/compose-environments/rapids1/compose/etc/conda/cuda_11.8/envs/rapids/lib/python3.10/site-packages/nvtx/nvtx.py", line 101, in inner
    result = func(*args, **kwargs)
  File "/raid/bdice/compose-environments/rapids1/cudf/python/cudf/cudf/core/udf/utils.py", line 141, in _get_udf_return_type
    ptx, output_type = cudautils.compile_udf(func, compile_sig)
  File "/raid/bdice/compose-environments/rapids1/cudf/python/cudf/cudf/utils/cudautils.py", line 243, in compile_udf
    key = make_cache_key(udf, type_signature)
  File "/raid/bdice/compose-environments/rapids1/cudf/python/cudf/cudf/utils/cudautils.py", line 198, in make_cache_key
    codebytes = udf.__code__.co_code
AttributeError: 'functools.partial' object has no attribute '__code__'. Did you mean: '__call__'?
```

This is failing because `make_cache_key` is trying to access an attribute that doesn't exist for function partials. This is a known limitation of function partials. I have dealt with this exact problem before. If the `__code__.co_code` attribute is not available, we must cache on function _identity_ rather than function contents. In other words:
```python
try:
  # Generate key using hash(f.__code__.co_code)
except AttributeError:
  # Generate key using hash(f)
```

**Comment by brandon-b-miller** [comment]
This is the same general problem as https://github.com/rapidsai/cudf/issues/11595.

**Comment by brandon-b-miller** [comment]
@bdice even if we can cache these I don't think we can proceed to JIT them, see https://github.com/numba/numba/issues/4587. I think the cleanest solution here is to simply reject them from `_can_be_jitted` and fall back to iterative groupby apply.

**Comment by brandon-b-miller** [comment]
Prior to https://github.com/rapidsai/cudf/pull/13113 the default was iterative, now it will make an attempt to JIT the function first and fall back to the iterative approach if it that fails. The catch here was that the piece of code that makes the initial JIT attempt couldn't handle `partial` due to the way it wraps callables.

**Comment by ayushdg** [comment]
Makes sense. Thanks for the clarification.
