### ISSUE TITLE
[BUG]: cudf fails to compile with g++-13.1 and nvcc 12.5.4

### ISSUE THREAD

**Issue by bernhardmgruber** [rapidsai/cudf#16395]
**Describe the bug**
cudf fails to compile with g++-13.1 and nvcc 12.5.4:
```
/usr/include/c++/13/bits/alloc_traits.h(68): error: static assertion failed with "allocator_traits<A>::rebind_alloc<A::value_type> must be A"
   static_assert(is_same<
   ^
          detected during:
            instantiation of class "std::__allocator_traits_base::__rebind<_Tp, _Up, std::__void_t<_Tp::rebind<_Up>::other>> [with _Tp=cudf::detail::cuco_allocator, _Up=cuco::detail::window<cudf::size_type, 1>]" at line 95
            instantiation of type "std::__alloc_rebind<cudf::detail::cuco_allocator, cuco::detail::window<cudf::size_type, 1>>" at line 228
            instantiation of type "std::allocator_traits<_Alloc>::rebind_alloc<cuco::detail::window<cudf::size_type, 1>> [with _Alloc=cudf::detail::cuco_allocator]" at line 69 of /yolo/cudf/cpp/build/_deps/cuco-src/include/cuco/aow_storage.cuh
            instantiation of class "cuco::aow_storage<T, WindowSize, Extent, Allocator> [with T=cudf::size_type, WindowSize=1, Extent=cuco::window_extent<cudf::size_type, 18446744073709551615UL>, Allocator=cudf::detail::cuco_allocator]" at line 32 of /yolo/cudf/cpp/build/_deps/cuco-src/include/cuco/detail/storage/storage.cuh
            instantiation of class "cuco::detail::storage<StorageImpl, T, Extent, Allocator> [with StorageImpl=cuco::storage<1>, T=cudf::size_type, Extent=cuco::window_extent<cudf::size_type, 18446744073709551615UL>, Allocator=cudf::detail::cuco_allocator]" at line 100 of /yolo/cudf/cpp/build/_deps/cuco-src/include/cuco/detail/open_addressing/open_addressing_impl.cuh
            instantiation of class "cuco::detail::open_addressing_impl<Key, Value, Extent, Scope, KeyEqual, ProbingScheme, Allocator, Storage> [with Key=cudf::size_type, Value=cudf::size_type, Extent=cudf::size_type, Scope=cuda::std::__4::thread_scope_device, KeyEqual=cudf::experimental::row::equality::device_row_comparator<true, cudf::nullate::DYNAMIC, cudf::experimental::row::equality::nan_equal_physical_equality_comparator>, ProbingScheme=cudf::groupby::detail::hash::<unnamed>::probing_scheme_type, Allocator=cudf::detail::cuco_allocator, Storage=cuco::storage<1>]" at line 96 of /yolo/cudf/cpp/build/_deps/cuco-src/include/cuco/static_set.cuh
            instantiation of class "cuco::static_set<Key, Extent, Scope, KeyEqual, ProbingScheme, Allocator, Storage> [with Key=cudf::size_type, Extent=cudf::size_type, Scope=cuda::std::__4::thread_scope_device, KeyEqual=cudf::experimental::row::equality::device_row_comparator<true, cudf::nullate::DYNAMIC, cudf::experimental::row::equality::nan_equal_physical_equality_comparator>, ProbingScheme=cudf::groupby::detail::hash::<unnamed>::probing_scheme_type, Allocator=cudf::detail::cuco_allocator, Storage=cuco::storage<1>]" at line 579 of /yolo/cudf/cpp/src/groupby/hash/groupby.cu
            instantiation of function "lambda [](auto)->auto [with <auto-1>=cudf::experimental::row::equality::device_row_comparator<true, cudf::nullate::DYNAMIC, cudf::experimental::row::equality::nan_equal_physical_equality_comparator>]" at line 616 of /yolo/cudf/cpp/src/groupby/hash/groupby.cu

1 error detected in the compilation of "/yolo/cudf/cpp/src/groupby/hash/groupby.cu".
```

**Steps/Code to reproduce bug**

* clone `https://github.com/rapidsai/cudf` (tried both, the default branch and `main`)
* within the git repo root: `./build.sh libcudf tests -n`

**Expected behavior**
A successful compilation.

**Environment overview (please complete the following information)**
 - Environment location: docker image `rapidsai/devcontainers:24.08-cpp-gcc13-cuda12.5`
 - Method of cuDF install: N/A

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     Not inside a git repository
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=23.04
     DISTRIB_CODENAME=lunar
     DISTRIB_DESCRIPTION="Ubuntu 23.04"
     PRETTY_NAME="Ubuntu 23.04"
     NAME="Ubuntu"
     VERSION_ID="23.04"
     VERSION="23.04 (Lunar Lobster)"
     VERSION_CODENAME=lunar
     ID=ubuntu
     ID_LIKE=debian
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     UBUNTU_CODENAME=lunar
     LOGO=ubuntu-logo
     Linux 7708879737b9 6.8.0-38-generic #38-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:25:01 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Thu Jul 25 09:39:29 2024
     +-----------------------------------------------------------------------------------------+
     | NVIDIA-SMI 555.42.06              Driver Version: 555.42.06      CUDA Version: 12.5     |
     |-----------------------------------------+------------------------+----------------------+
     | GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
     |                                         |                        |               MIG M. |
     |=========================================+========================+======================|
     |   0  NVIDIA RTX A6000               Off |   00000000:41:00.0  On |                  Off |
     | 30%   53C    P8             35W /  300W |     774MiB /  49140MiB |      8%      Default |
     |                                         |                        |                  N/A |
     +-----------------------------------------+------------------------+----------------------+
     |   1  NVIDIA GeForce GT 1030         Off |   00000000:61:00.0 Off |                  N/A |
     | N/A   33C    P8             N/A /   30W |       7MiB /   2048MiB |      0%      Default |
     |                                         |                        |                  N/A |
     +-----------------------------------------+------------------------+----------------------+
     
     +-----------------------------------------------------------------------------------------+
     | Processes:                                                                              |
     |  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
     |        ID   ID                                                               Usage      |
     |=========================================================================================|
     +-----------------------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:                         x86_64
     CPU op-mode(s):                       32-bit, 64-bit
     Address sizes:                        48 bits physical, 48 bits virtual
     Byte Order:                           Little Endian
     CPU(s):                               64
     On-line CPU(s) list:                  0-63
     Vendor ID:                            AuthenticAMD
     Model name:                           AMD Ryzen Threadripper PRO 5975WX 32-Cores
     CPU family:                           25
     Model:                                8
     Thread(s) per core:                   2
     Core(s) per socket:                   32
     Socket(s):                            1
     Stepping:                             2
     Frequency boost:                      enabled
     CPU(s) scaling MHz:                   28%
     CPU max MHz:                          7006.6401
     CPU min MHz:                          1800.0000
     BogoMIPS:                             7186.57
     Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local user_shstk clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin brs arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm debug_swap
     Virtualization:                       AMD-V
     L1d cache:                            1 MiB (32 instances)
     L1i cache:                            1 MiB (32 instances)
     L2 cache:                             16 MiB (32 instances)
     L3 cache:                             128 MiB (4 instances)
     NUMA node(s):                         1
     NUMA node0 CPU(s):                    0-63
     Vulnerability Gather data sampling:   Not affected
     Vulnerability Itlb multihit:          Not affected
     Vulnerability L1tf:                   Not affected
     Vulnerability Mds:                    Not affected
     Vulnerability Meltdown:               Not affected
     Vulnerability Mmio stale data:        Not affected
     Vulnerability Reg file data sampling: Not affected
     Vulnerability Retbleed:               Not affected
     Vulnerability Spec rstack overflow:   Vulnerable: Safe RET, no microcode
     Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
     Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
     Vulnerability Spectre v2:             Mitigation; Retpolines; IBPB conditional; IBRS_FW; STIBP always-on; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
     Vulnerability Srbds:                  Not affected
     Vulnerability Tsx async abort:        Not affected
     
     ***CMake***
     /usr/bin/cmake
     cmake version 3.29.6
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 13.1.0-2ubuntu2~23.04) 13.1.0
     Copyright (C) 2023 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2024 NVIDIA Corporation
     Built on Wed_Apr_17_19:19:55_PDT_2024
     Cuda compilation tools, release 12.5, V12.5.40
     Build cuda_12.5.r12.5/compiler.34177558_0
     
     ***Python***
     /home/coder/.local/share/venvs/cccl/bin/python
     Python 3.11.4
     
     ***Environment Variables***
     PATH                            : /home/coder/.local/share/venvs/cccl/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
     LD_LIBRARY_PATH                 : /usr/local/nvidia/lib:/usr/local/nvidia/lib64
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    :
     PYTHON_PATH                     : /usr/local/python/current
     
     conda not found
     ***pip packages***
     /home/coder/.local/share/venvs/cccl/bin/pip
     Package      Version
     ------------ -------
     cfgv         3.4.0
     distlib      0.3.8
     filelock     3.15.4
     identify     2.6.0
     lit          18.1.8
     nodeenv      1.9.1
     pip          24.1.2
     platformdirs 4.2.2
     pre-commit   3.7.1
     psutil       6.0.0
     PyYAML       6.0.1
     setuptools   70.3.0
     virtualenv   20.26.3
     wheel        0.43.0
     
</pre></details>

**Comment by davidwendt** [comment]
@PointKernel This appears to be coming from deep in `cuco::static_set`

**Comment by PointKernel** [comment]
Update: once https://github.com/NVIDIA/cuCollections/pull/567 gets merged, cuco builds fine with the given image. Something else is wrong on the libcudf side.
