### PR TITLE
Fix compile issue in `json_chunked_reader.cpp`

### PR DESCRIPTION
**Pull request by ttnghia**
This issue was introduced in https://github.com/rapidsai/cudf/pull/12017 merged, which triggers compiler error on some systems:
```
../tests/io/json_chunked_reader.cpp: In function 'std::vector<cudf::io::table_with_metadata> skeleton_for_parellel_chunk_reader(cudf::host_span<std::unique_ptr<cudf::io::datasource> >, const cudf::io::json_reader_options&, int32_t, rmm::cuda_stream_view, rmm::mr::device_memory_resource*)':
../tests/io/json_chunked_reader.cpp:78:19: error: loop variable '<structured bindings>' creates a copy from type 'const std::pair<int, int>' [-Werror=range-loop-construct]
   78 |   for (auto const [chunk_start, chunk_end] : record_ranges) {
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~
../tests/io/json_chunked_reader.cpp:78:19: note: use reference type to prevent copying
   78 |   for (auto const [chunk_start, chunk_end] : record_ranges) {
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~
      |                   &
```

Fixing it is just by following the compiler recommendation: "use reference type to prevent copying".

### CODE REVIEW

**Review by davidwendt — APPROVED** [review]

**Review by PointKernel — APPROVED** [review]

**Comment by ttnghia** [comment]
@gpucibot merge
