### PR TITLE
Fix benchmarks to work with new aggregation types

### PR DESCRIPTION
**Pull request by davidwendt**
Fixes benchmarks compile errors introduced by #10357 

Example:
```
/cudf/cpp/benchmarks/reduction/reduce.cpp: In function ‘void BM_reduction(benchmark::State&, const std::unique_ptr<cudf::aggregation>&)’:
/cudf/cpp/benchmarks/reduction/reduce.cpp:52:46: error: invalid initialization of reference of type ‘const std::unique_ptr<cudf::reduce_aggregation>&’ from expression of type ‘const std::unique_ptr<cudf::aggregation>’
   52 |     auto result = cudf::reduce(input_column, agg, output_dtype);
```

Aggregation types for reduce and scan were modified to include template types.

### CODE REVIEW

**Review by vyasr — APPROVED** [review]
Thanks for fixing this! I merged these changes locally and verified that they fix the build.

**Review by nvdbaranec — APPROVED** [review]

**Comment by vyasr** [comment]
@gpucibot merge
