### PR TITLE
Add braces to prefetch_noexcept location var to fix clang-tidy reported error

### PR DESCRIPTION
**Pull request by davidwendt**
## Description
Fixes a clang-tidy reported error:
```
cpp/src/utilities/prefetch.cpp:54:5: error: suggest braces around initialization of subobject [clang-diagnostic-missing-braces,-warnings-as-errors]
   54 |     device_id.value()};
      |     ^~~~~~~~~~~~~~~~~
      |     {                }
```
Reference: https://github.com/rapidsai/cudf/actions/runs/28523775732/job/84555399492?pr=23031#step:13:1460

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by bdice — APPROVED** [review]
I guess that's fine but I don't see why it's needed.

**Comment by bdice** [comment]
I got curious about why this had changed. We updated the `latest` ci-conda tag to CUDA 13.3, which triggered this.

In CUDA 13.2, `cudaMemLocation` had:

```cpp
enum cudaMemLocationType type;
int id;
```

In CUDA 13.3, it became:

```cpp
enum cudaMemLocationType type;
union {
    int id;
};
```

File: cpp/src/utilities/prefetch.cpp [hunk 1]
```diff
@@ -51,7 +51,7 @@ cudaError_t prefetch_noexcept(void const* ptr,
 #if defined(CUDART_VERSION) && CUDART_VERSION >= 13000
   cudaMemLocation location{
     (device_id.value() == cudaCpuDeviceId) ? cudaMemLocationTypeHost : cudaMemLocationTypeDevice,
-    device_id.value()};
+    {device_id.value()}};
```
Comment (bdice) [inline cpp/src/utilities/prefetch.cpp:54]: An alternative fix that should work with CUDA 13.0-13.2 or CUDA 13.3+ is this (untested):

```suggestion
  cudaMemLocation location{};
  location.type = (device_id.value() == cudaCpuDeviceId)
                    ? cudaMemLocationTypeHost
                    : cudaMemLocationTypeDevice;
  location.id = device_id.value();
```

Comment (davidwendt) [reply cpp/src/utilities/prefetch.cpp:54]: This suggestion appears to be a "declare and delay initialization" anti-pattern which prevents `location` from being a constant variable.

**Comment by davidwendt** [comment]
Claude gave me this explanation:

> The `cudaMemLocation` aggregate (introduced in CUDA 13's `driver_types.h`) is initialized with a multi-line brace-init-list. Clang's brace-elision checker flags the second member (`id`) because the first initializer is a line-broken conditional expression, and wants each subobject's initializer explicitly braced rather than relying on elision.

**Review by Matt711 — APPROVED** [review]

**Review by vyasr — APPROVED** [review]

**Review by PointKernel — APPROVED** [review]
