### PR TITLE
Include <cstddef> to fix compilation of parquet reader on GCC 11.

### PR DESCRIPTION
**Pull request by bdice**
Includes `<cstddef>` for `ptrdiff_t` in `parquet/compact_protocol_reader.hpp`. Compilation fails on GCC 11 without this include. Targeting 22.04 since this was broken yesterday in #10063.

Error output:
```
cudf/cpp/src/io/parquet/compact_protocol_reader.hpp:51:17: error: 'ptrdiff_t' does not name a type
   51 |   [[nodiscard]] ptrdiff_t bytecount() const noexcept { return m_cur - m_base; }
      |
cudf/cpp/src/io/parquet/compact_protocol_reader.hpp:22:1: note: 'ptrdiff_t' is defined in header '<cstddef>'; did you forget to '#include <cstddef>'?
```

Also includes `<optional>` in `cpp/include/cudf/table/experimental/row_operators.cuh`, which was broken by #10164.

### CODE REVIEW

**Review by codereport — APPROVED** [review]
lgtm :+1:

**Review by PointKernel — APPROVED** [review]

**Comment by bdice** [comment]
@gpucibot merge
