### ISSUE TITLE
[QST] Disabling  decimal128 support

### ISSUE THREAD

**Issue by benjha** [rapidsai/cudf#11219]
Hi cudf team,

I am building from source cudf on pcc64le (Summit cluster)  using CUDA 11.4 and driver 450.80.02

```
...
[ 11%] Building CXX object CMakeFiles/cudf.dir/src/aggregation/result_cache.cpp.o
[ 11%] Building CXX object CMakeFiles/cudf.dir/src/ast/expression_parser.cpp.o
/sw/summit/ums/gen119/nvrapids/src/nvrapids_v22.06.00_src/cudf_v22.06.00/cpp/include/cudf/utilities/type_dispatcher.hpp(522): error: "numeric::decimal128" contains a 128-bit integer, which is not supported in device code
          detected during instantiation of "decltype(auto) cudf::type_dispatcher(cudf::data_type, Functor, Ts &&...) [with IdTypeMap=cudf::id_to_type_impl, Functor=cudf::detail::unary_relationally_comparable_functor, Ts=<>]" 
/sw/summit/ums/gen119/nvrapids/src/nvrapids_v22.06.00_src/cudf_v22.06.00/cpp/include/cudf/utilities/traits.hpp(149): here
...
```

Is there way to disable decimal128 support ? 

From what I checked so far decimal128 support started in CUDA 11.5 so I would expect support should be disabled when finding older CUDA version, right ?

Thanks,

**Comment by quasiben** [comment]
I dont' think we can disable decimal 128 support.  Instead of building on 11.4, you could build with 11.5 -> 11.7 then rely on CEC for CUDA 11.0->11.4 backwards compatibility.  This is how we are getting older CUDA Driver/Toolkit while we build conda packages in a 11.7 environment

**Comment by benjha** [comment]
Thanks,

I recompiled using the  CUDA 11.5 module available on Summit
