### ISSUE TITLE
[FEA] Move pandas-related notes from Notes to pandas-compat

### ISSUE THREAD

**Issue by vyasr** [rapidsai/cudf#11460]
**Is your feature request related to a problem? Please describe.**
#8643 introduced a new rST directive `pandas-compat` to our documentation that allows us to collect all documentation relating to differences between cuDF methods and pandas methods. That directive enables us to much more effectively indicate to users when our behavior differs from pandas. However, we have not since made much use of this directive. Many docstrings still contain `Notes` sections that are essentially just descriptions of how a class/function/method differs from pandas.

**Describe the solution you'd like**
We should convert all pandas-related `Notes` sections of docstrings into `pandas-compat` sections. Doing so should be quite straightforward by simply searching for the header `Notes` in all files containing public APIs. For examples on how to use the `pandas-compat` directive, see #8643.

**Describe alternatives you've considered**
None

**Additional context**
There are likely many other places where we differ from pandas that are either 1) undocumented or 2) documented in different ways. We should also aim to improve that documentation. However, that is a nebulous target since it's not immediately clear where all those places are, so this issue is just focusing on the more specific goal of replacing `Notes` sections, which can be easily searched for and replaced as needed.

**Comment by Touutae-lab** [comment]
I would like to help this issues.

**Comment by shwina** [comment]
Hi @Touutae-lab -- thanks for your interest in contributing! This would absolutely be a welcome addition to cuDF. Please feel free to comment here if you need any help as you work on this issue.

**Comment by Touutae-lab** [comment]
### Hi, I have some question how should i handle this ?

![Screenshot from 2023-01-28 16-09-24](https://user-images.githubusercontent.com/58826535/215257559-5fbcbe4f-485f-405d-83b5-7105dda3247a.png)

### so I handle like this
![Screenshot from 2023-01-28 16-23-12](https://user-images.githubusercontent.com/58826535/215258392-b35e2ecb-4ca8-4f2c-9ea3-0418a622e5bd.png)

### after compilation it not showing in the last `PandasCompat.html`
```python
"""
        Examples
        --------
        >>> import cudf
        >>> df = cudf.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
        >>> df
           A  B
        0  1  4
        1  2  5
        2  3  6

        Rename columns using a mapping:

        >>> df.rename(columns={"A": "a", "B": "c"})
           a  c
        0  1  4
        1  2  5
        2  3  6

        Rename index using a mapping:

        >>> df.rename(index={0: 10, 1: 20, 2: 30})
            A  B
        10  1  4
        20  2  5
        30  3  6
        
        .. pandas-compat::
            **DataFrame.rename**
            
            Note: Rename will not overwrite column names. If a list with duplicates is
            passed, column names will be postfixed with a number.
        """
```

**Comment by Touutae-lab** [comment]
i currently working in [branch-23.02](https://github.com/rapidsai/cudf/tree/branch-23.02) it seem `make html` result a lot of bug and not working property.

**Comment by Touutae-lab** [comment]
I try to looking into Sphix documentation. It seem i need to fix this,
 but i can't where it refer to.
```
WARNING: [autosummary] failed to import cudf.DataFrame.quantiles.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.DataFrame'
* ImportError: 
* AttributeError: type object 'DataFrame' has no attribute 'quantiles'
WARNING: [autosummary] failed to import cudf.Index.argsort.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* ImportError: 
* AttributeError: type object 'Index' has no attribute 'argsort'
WARNING: [autosummary] failed to import cudf.Index.astype.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* AttributeError: type object 'Index' has no attribute 'astype'
* ImportError: 
WARNING: [autosummary] failed to import cudf.Index.dtype.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* ImportError: 
* AttributeError: type object 'Index' has no attribute 'dtype'
WARNING: [autosummary] failed to import cudf.Index.empty.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* ImportError: 
* AttributeError: type object 'Index' has no attribute 'empty'
WARNING: [autosummary] failed to import cudf.Index.equals.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* ImportError: 
* AttributeError: type object 'Index' has no attribute 'equals'
WARNING: [autosummary] failed to import cudf.Index.factorize.
Possible hints:
* AttributeError: type object 'Index' has no attribute 'factorize'
* ModuleNotFoundError: No module named 'cudf.Index'
* ImportError: 
WARNING: [autosummary] failed to import cudf.Index.is_mixed.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* ImportError: 
* AttributeError: type object 'Index' has no attribute 'is_mixed'
WARNING: [autosummary] failed to import cudf.Index.is_unique.
Possible hints:
* AttributeError: type object 'Index' has no attribute 'is_unique'
* ModuleNotFoundError: No module named 'cudf.Index'
* ImportError: 
WARNING: [autosummary] failed to import cudf.Index.max.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* ImportError: 
* AttributeError: type object 'Index' has no attribute 'max'
WARNING: [autosummary] failed to import cudf.Index.memory_usage.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* AttributeError: type object 'Index' has no attribute 'memory_usage'
* ImportError: 
WARNING: [autosummary] failed to import cudf.Index.min.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* ImportError: 
* AttributeError: type object 'Index' has no attribute 'min'
WARNING: [autosummary] failed to import cudf.Index.name.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* ImportError: 
* AttributeError: type object 'Index' has no attribute 'name'
WARNING: [autosummary] failed to import cudf.Index.ndim.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* AttributeError: type object 'Index' has no attribute 'ndim'
* ImportError: 
WARNING: [autosummary] failed to import cudf.Index.searchsorted.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* AttributeError: type object 'Index' has no attribute 'searchsorted'
* ImportError: 
WARNING: [autosummary] failed to import cudf.Index.shape.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* AttributeError: type object 'Index' has no attribute 'shape'
* ImportError: 
WARNING: [autosummary] failed to import cudf.Index.shift.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* AttributeError: type object 'Index' has no attribute 'shift'
* ImportError: 
WARNING: [autosummary] failed to import cudf.Index.str.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* AttributeError: type object 'Index' has no attribute 'str'
* ImportError: 
WARNING: [autosummary] failed to import cudf.Index.to_arrow.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* AttributeError: type object 'Index' has no attribute 'to_arrow'
* ImportError: 
WARNING: [autosummary] failed to import cudf.Index.to_cupy.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* ImportError: 
* AttributeError: type object 'Index' has no attribute 'to_cupy'
WARNING: [autosummary] failed to import cudf.Index.to_list.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* ImportError: 
* AttributeError: type object 'Index' has no attribute 'to_list'
WARNING: [autosummary] failed to import cudf.Index.to_numpy.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* ImportError: 
* AttributeError: type object 'Index' has no attribute 'to_numpy'
WARNING: [autosummary] failed to import cudf.Index.where.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Index'
* ImportError: 
* AttributeError: type object 'Index' has no attribute 'where'
WARNING: [autosummary] failed to import cudf.Series.applymap.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Series'
* AttributeError: type object 'Series' has no attribute 'applymap'
* ImportError:
```

**Comment by Touutae-lab** [comment]
Hi, i'm asking about `code-commit` for easy to navigate change. because it my first open source.

when i finished API such as DataFrame it would be first commit with `DataFrame convert #1`
or should i just finished all task then commit.

**Comment by Touutae-lab** [comment]
### BUG Report

can't convert Note froms `DataFrame.mode`
![image](https://user-images.githubusercontent.com/58826535/215328052-dac20fb8-7377-442f-8bf1-cc1b2582aa5d.png)

convert to 
![image](https://user-images.githubusercontent.com/58826535/215328475-19b72d4f-73ba-4a08-b07f-56f29b96e104.png)

```
Extension error (numpydoc.numpydoc):
Handler <function mangle_signature at 0x7fe25c23d630> for event 'autodoc-process-signature' threw an exception (exception: Error parsing See Also entry '.. pandas-compat::' in the docstring of mode in /home/touutae/miniconda3/envs/cudf_dev/lib/python3.10/contextlib.py.)
make: *** [Makefile:20: html] Error 2
```

it only happened when edited `DataFrame.mode`

**Comment by Touutae-lab** [comment]
@shwina 
Hi,
I already working on some that i can convert can you check please ?

**Comment by vyasr** [comment]
This was completed in #12641
