### PR TITLE
Fix debug compile error in gather_struct_tests.cpp

### PR DESCRIPTION
**Pull request by davidwendt**
Building libcudf in debug resulted in a compile error introduced by #8527 

```
../tests/copying/gather_struct_tests.cpp:87:32: error: suggest parentheses around ‘&&’ within ‘||’ [-Werror=parentheses]
   87 |       assert(gather_index >= 0 && gather_index < gather_map.size() ||
      |              ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This error only shows in a debug build. This PR fixes the this code by applying the parentheses as the error suggests.

### CODE REVIEW

**Comment by ttnghia** [comment]
This is duplicate of https://github.com/rapidsai/cudf/pull/8565

**Review by gerashegalov — APPROVED** [review]

**Review by ttnghia — APPROVED** [review]

**Review by mythrocks — APPROVED** [review]

**Comment by vuule** [comment]
@gpucibot merge
